// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchNameMajorAvailableTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchNameMajorAvailable() {
    driver.get("http://localhost:8080//login");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("susi@email.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123456");
    driver.findElement(By.id("btnLogin")).click();
    driver.findElement(By.cssSelector("#BFB20000 span:nth-child(2)")).click();
    driver.findElement(By.cssSelector("#BFB20002 span")).click();
    driver.findElement(By.id("memberName")).click();
    driver.findElement(By.id("memberName")).sendKeys("Budi");
    driver.findElement(By.id("majors")).click();
    driver.findElement(By.id("majors")).sendKeys("Teknik Kimia");
    driver.findElement(By.id("btnSearch")).click();
    assertThat(driver.findElement(By.cssSelector("td:nth-child(4)")).getText(), is("Budi"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(5) > p")).getText(), is("Teknik Kimia DIII Teknik Kimia"));
  }
}
